# Generated by Django 2.0.7 on 2020-01-06 22:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_id', models.CharField(max_length=4, unique=True)),
                ('kunde_navn', models.CharField(max_length=30)),
                ('kunde_installation', models.TextField(blank=True, null=True)),
                ('kunde_adresse', models.TextField(blank=True, help_text='Gadenavn, nr., Postnummer og By', null=True)),
                ('kontaktperson', models.CharField(max_length=30)),
                ('kontakt_tlf', models.CharField(max_length=10)),
                ('kontakt_mail', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('kunde_navn',),
            },
        ),
        migrations.CreateModel(
            name='Opgaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_navn', models.CharField(max_length=30)),
                ('opgave_beskrivelse', models.TextField(blank=True, null=True)),
                ('noter', models.TextField(blank=True, null=True)),
                ('tid_brugt', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Ikke angivet'), (2, 'Startet'), (3, 'Halvvejs'), (4, 'Sidste Detaljer'), (5, 'Færdig')], default=1)),
                ('prioritet', models.IntegerField(choices=[(1, 'Højeste'), (2, 'Mellem'), (3, 'Laveste')], default=3)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('ansvarlig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('prioritet', 'deadline'),
            },
        ),
    ]
