# Generated by Django 3.0 on 2019-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opgaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_navn', models.CharField(max_length=20)),
                ('ansvarlig', models.IntegerField(choices=[(1, 'Alle'), (2, 'Magnus'), (3, 'Martin'), (4, 'Alex'), (5, 'Sebastian')], default=1)),
                ('opgave_beskrivelse', models.TextField(blank=True, null=True)),
                ('noter', models.TextField()),
                ('tid_brugt', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Mangler'), (2, 'Startet'), (3, 'Halvvejs'), (4, 'Sidste Detaljer'), (5, 'Færdig')], default=1)),
                ('prioritet', models.IntegerField(choices=[(1, 'Høj'), (2, 'Mellem'), (3, 'Lav')], default=3)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
