# Generated by Django 2.0.7 on 2020-01-03 03:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_id', models.CharField(max_length=4, unique=True)),
                ('kunde_navn', models.CharField(max_length=30)),
                ('kunde_installation', models.TextField(blank=True, null=True)),
                ('kunde_adresse', models.TextField(blank=True, help_text='Gadenavn, nr., Postnummer og By', null=True)),
                ('kontaktperson', models.CharField(max_length=30)),
                ('kontakt_tlf', models.CharField(max_length=10)),
                ('kontakt_mail', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('kunde_navn',),
            },
        ),
        migrations.AlterModelOptions(
            name='opgaver',
            options={'ordering': ('prioritet', 'deadline')},
        ),
        migrations.AddField(
            model_name='opgaver',
            name='afsluttet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='ansvarlig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='kunde_navn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='noter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='prioritet',
            field=models.IntegerField(choices=[(1, 'Højeste'), (2, 'Mellem'), (3, 'Laveste')], default=3),
        ),
        migrations.AlterField(
            model_name='opgaver',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ikke angivet'), (2, 'Startet'), (3, 'Halvvejs'), (4, 'Sidste Detaljer'), (5, 'Færdig')], default=1),
        ),
    ]
