# Generated by Django 2.0.7 on 2020-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgaver',
            name='fælles',
            field=models.BooleanField(default=False),
        ),
    ]
