# Generated by Django 2.0.7 on 2020-01-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0002_auto_20200103_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opgaver',
            name='afsluttet',
        ),
    ]
